openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Users
  license:
    name: MIT
servers:
  - url: /department/
components:
  schemas:
    User2:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Users2:
      type: array
      items:
        $ref: "#/components/schemas/User2"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
